USE [master]
GO

/****** Object:  Database [Products]    Script Date: 12/7/2021 00:19:35 ******/
DROP DATABASE [Products]
GO

/****** Object:  Database [Products]    Script Date: 12/7/2021 00:19:35 ******/
CREATE DATABASE [Products]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Products', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Products.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Products_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Products_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Products].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Products] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Products] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Products] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Products] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Products] SET ARITHABORT OFF 
GO

ALTER DATABASE [Products] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Products] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Products] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Products] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Products] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Products] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Products] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Products] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Products] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Products] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Products] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Products] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Products] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Products] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Products] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Products] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Products] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Products] SET RECOVERY FULL 
GO

ALTER DATABASE [Products] SET  MULTI_USER 
GO

ALTER DATABASE [Products] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Products] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Products] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Products] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Products] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Products] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Products] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Products] SET  READ_WRITE 
GO

